try {
  // will be a reference error
  myFunction();
} catch(error) {
  console.log(error)
}